const EAST_ASIA_TAGS = [
  'k-pop',
  'j-pop',
  'city pop',
  'k-indie',
  'c-pop',
  'cantopop',
  'enka',
  'vkei',
  'anime',
  'taiwan indie',
] as const

const SOUTHEAST_ASIA_TAGS = [
  'thai pop',
  'vietnamese pop',
  'filipiniana',
  'singapore pop',
  'indonesian indie',
] as const

const SOUTH_ASIA_TAGS = [
  'bollywood',
  'tamil cinema',
  'telugu cinema',
  'kannada cinema',
  'malayalam cinema',
  'bhangra',
  'qawwali',
  'indian classical',
  'hindustani',
  'carnatic',
  'pakistani pop',
  'bangladeshi folk',
] as const

const MIDDLE_EAST_TAGS = [
  'arabic pop',
  'rai',
  'gnawa',
  'maqam',
  'turkish folk',
  'turkish pop',
  'anatolian rock',
  'persian pop',
  'israeli folk',
  'levantine pop',
] as const

const AFRICA_TAGS = [
  'afrobeats',
  'amapiano',
  'gqom',
  'highlife',
  'congolese rumba',
  'soukous',
  'juju',
  'griot',
  'makossa',
  'mbalax',
  'sudanese pop',
  'ethiowave',
  'ethiopian jazz',
  'rwandan pop',
  'tanzanian pop',
  'amapiano',
  'kwaito',
] as const

const LATIN_AMERICA_TAGS = [
  'bossa nova',
  'mpb',
  'tropicália',
  'forró',
  'sertanejo',
  'axé',
  'bebop',
  'samba',
  'choro',
  'bachata',
  'merengue',
  'salsa',
  'cumbia',
  'champeta',
  'reggaeton',
  'trap latino',
  'corridos',
  'banda',
  'ranchera',
  'tango',
  'bolero',
  'son cubano',
] as const

const EUROPE_TAGS = [
  'french pop',
  'chanson',
  'gypsy jazz',
  'flamenco',
  'krautrock',
  'deutsche elektronische musik',
  'soviet wave',
  'russian punk',
  'greek pop',
  'scandinavian indie',
  'britpop',
  'scottish folk',
  'irish folk',
  'punk',
  'post-punk',
] as const

const NORTH_AMERICA_TAGS = [
  'country',
  'bluegrass',
  'americana',
  'alt-country',
  'outlaw country',
  'country pop',
  'country rap',
  'corridos tumbados',
  'folk',
  'blues',
  'jazz',
  'bebop',
  'cool jazz',
  'free jazz',
  'soul',
  'neo soul',
  'motown',
  'funk',
  'disco',
  'spoken word',
] as const

const BLUES_AND_SOUL_TAGS = [
  'delta blues',
  'chicago blues',
  'memphis soul',
  'philadelphia soul',
  'rnb',
  'contemporary rnb',
  'experimental soul',
] as const

const POP_VARIANT_TAGS = [
  'art pop',
  'dream pop',
  'alt-pop',
  'synth-pop',
  'electropop',
  'dance-pop',
  'synthwave',
  'vaporwave',
  'chillwave',
  'bedroom pop',
  'pop punk',
  'power pop',
] as const

const ROCK_VARIANT_TAGS = [
  'indie rock',
  'alternative rock',
  'alternative',
  'progressive rock',
  'psychedelic rock',
  'psychedelic pop',
  'shoegaze',
  'post-rock',
  'noise rock',
  'glam rock',
  'hard rock',
  'rock and roll',
  'garage rock',
  'surf rock',
  'stoner rock',
  'grunge',
] as const

const METAL_VARIANT_TAGS = [
  'metal',
  'heavy metal',
  'thrash metal',
  'death metal',
  'black metal',
  'doom metal',
  'symphonic metal',
  'metalcore',
  'nu metal',
  'alternative metal',
  'progressive metal',
  'industrial metal',
  'folk metal',
  'viking metal',
  'melodic metal',
] as const

const METAL_SUBGENRE_TAGS = [
  'screamo',
  'skramz',
  'mathcore',
  'deathcore',
  'hardcore',
  'post-hardcore',
] as const

const ELECTRONIC_AND_DANCE_TAGS = [
  'electronic',
  'house',
  'deep house',
  'acid house',
  'tech house',
  'minimal house',
  'progressive house',
  'techno',
  'minimal techno',
  'industrial techno',
  'acid techno',
  'detroit techno',
  'berlijn techno',
  'trance',
  'progressive trance',
  'psytrance',
  'goa trance',
  'downtempo',
  'ambient',
  'dark ambient',
  'drone',
  'ambient techno',
  'IDM',
  'glitch',
  'leftfield',
  'experimental electronic',
  'electroacoustic',
  'musique concrète',
  'industrial',
  'industrial noise',
  'power electronics',
] as const

const ELECTRONIC_DANCE_SUBGENRE_TAGS = [
  'dubstep',
  'riddim',
  'brostep',
  'wobble bass',
  'deep dubstep',
  'post-dubstep',
  'drum and bass',
  'jungle',
  'liquid funk',
  'liquid drum and bass',
  'neurofunk',
  'dnb',
  'breakcore',
  'hardcore',
  'happy hardcore',
  'uk garage',
  'dubstep garage',
  'grime',
  'garage',
  'uk funky',
  'complextro',
  'future bass',
  'trap',
  'future trap',
  'cloud rap',
  'witch house',
  'crunk',
  'electro house',
  'electro',
  'electro swing',
  'big room house',
  'progressive electro house',
] as const

const HIP_HOP_AND_RAP_TAGS = [
  'hip-hop',
  'rap',
  'underground hip-hop',
  'abstract hip-hop',
  'conscious hip-hop',
  'boom bap',
  'cloud rap',
  'emo rap',
  'emo hip-hop',
  'trap',
  'southern trap',
  'chicago trap',
  'memphis trap',
  'atlanta trap',
  'plugg',
  'plugg beats',
  'melodic trap',
  'dark trap',
  'future trap',
  'trap metal',
  'horrorcore',
  'gangsta rap',
  'west coast hip-hop',
  'east coast hip-hop',
  'midwest hip-hop',
  'southern hip-hop',
  'crunk',
  'snap music',
  'chopped and screwed',
  'phonk',
  'vaporhop',
  'jerk',
  'stepper',
  'digicore',
  'rage beats',
  'nerdcore',
] as const

const EXPERIMENTAL_AND_NICHE_TAGS = [
  'experimental',
  'noise',
  'avant-garde',
  'art music',
  'classical',
  'contemporary classical',
  'neo-classical',
  'minimalism',
  'symphonic',
  'orchestral',
  'chamber music',
  'baroque',
  'romantic',
  'opera',
  'musical theater',
  'soundtrack',
  'video game music',
  'chiptune',
  '8-bit',
  '16-bit',
  'bitpop',
  'demoscene',
  'breakbeat',
  'big beat',
  'trip hop',
  'downtempo',
  'lofi',
  'lo-fi hip-hop',
  'sample-based',
  'beat tape',
  'jazz fusion',
  'fusion',
  'world fusion',
  'ethno-jazz',
  'acid jazz',
  'smooth jazz',
  'jazz fusion',
] as const

const SPECIALTY_TAGS = [
  'comedy',
  'novelty',
  'children music',
  'spoken word',
  'poetry',
  'audiobook',
  'asmr',
  'vaporwave',
  'vaporhop',
  'hyperpunk',
  'hyperpop',
  'rage beats',
  'dark hyperpop',
  'metalblackgaze',
  'indietronica',
  'folktronica',
  'folkwave',
  'britwave',
  'hypermusicology',
  'maximalist',
  'minimalism',
  'microtonality',
  'aleatoric',
  'spectral music',
  'semiotics',
  'concrète',
  'live coding',
] as const

const NICHE_AND_USER_CREATED_TAGS = [
  'singer-songwriter',
  'acoustic',
  'unplugged',
  'stripped',
  'lo-fi acoustic',
  'folk rock',
  'contemporary folk',
  'anti-folk',
  'alt folk',
  'indie folk',
  'art rock',
  'avant-pop',
  'chamber pop',
  'chamber rock',
  'indie pop',
  'twee pop',
  'steampunk',
  'goblin core',
  'goblin music',
  'meme music',
  'dariacore',
  'hyperflip',
  'bubble bass',
  'cutecore',
  'kawaii metal',
  'furry',
  'pirate metal',
  'pirate black metal',
  'circus metal',
  'deathjazz',
  'fluxus',
  'happening',
  'performance art',
  'live art',
  'ritual ambient',
  'dark folk',
  'witch house',
  'darkwave',
  'coldwave',
  'ethereal wave',
  'new wave',
  'synth-punk',
  'synth-pop',
  'elektropunk',
  'pixel metal',
  'nintendocore',
  'gameboy music',
  'tracker music',
  'modular',
  'patch music',
  'patch sessions',
  'prepared piano',
  'extended techniques',
  'plunderphonics',
  'collage',
  'montage',
  'cut-up',
  'mashup',
  'bootleg',
  'parody',
  'satire',
  'absurdist music',
  'surreal',
  'oneiric',
  'dream music',
  'liminal',
  'backrooms',
  'uncanny valley',
  'proto-industrial',
  'pre-industrial',
  'post-industrial',
  'cyber',
  'cyberpunk',
  'synthgoth',
  'futurepop',
  'electro-goth',
  'medieval synth',
  'renaissance faire',
  'viking music',
  'celtic ambient',
  'druidic',
  'pagan',
  'neofolk',
] as const

export const PACK_TAGS = [
  ...EAST_ASIA_TAGS,
  ...SOUTHEAST_ASIA_TAGS,
  ...SOUTH_ASIA_TAGS,
  ...MIDDLE_EAST_TAGS,
  ...AFRICA_TAGS,
  ...LATIN_AMERICA_TAGS,
  ...EUROPE_TAGS,
  ...NORTH_AMERICA_TAGS,
  ...BLUES_AND_SOUL_TAGS,
  ...POP_VARIANT_TAGS,
  ...ROCK_VARIANT_TAGS,
  ...METAL_VARIANT_TAGS,
  ...METAL_SUBGENRE_TAGS,
  ...ELECTRONIC_AND_DANCE_TAGS,
  ...ELECTRONIC_DANCE_SUBGENRE_TAGS,
  ...HIP_HOP_AND_RAP_TAGS,
  ...EXPERIMENTAL_AND_NICHE_TAGS,
  ...SPECIALTY_TAGS,
  ...NICHE_AND_USER_CREATED_TAGS,
] as const

export type PackTag = (typeof PACK_TAGS)[number]
